#!/usr/bin/env python2.5

import sys
from getopt import getopt

from pair import cons, nil
import reader
import lx

def read_file(n):
    return reader.read(open(n).read())

opts, args = getopt(sys.argv[1:], 'mco:', [
        'module',
        'generate-c',
        'output=',
        ])

infile = args[0]
outfile = infile + 'c'
gen_c = False
module = False

for opt, val in opts:
    if opt in ('--generate-c', '-c'):
        gen_c = True
    elif opt in ('--module', '-m'):
        module = True
    elif opt in ('--output', '-o'):
        outfile = val

if len(sys.argv) < 2:
    print 'please give me a flie'
    sys.exit()

exps = read_file(infile)
if module:
    # ((fn () ...))
    exp = cons(cons(lx.fn_s, cons(nil, exps)), nil)
else:
    # (do ...)
    exp = cons(lx.do_s, exps)

code = lx.compile(exp, lx.S('val'), lx.S('next'), nil)
outfd = open(outfile, 'w')
if gen_c:
    if not outfile.endswith('.c'): raise 'bad output file name', outfile
    outhfile = outfile[:-2] + '.h'
    outhfd = open(outhfile, 'w')
    code.gen_c(infile.replace('.lx', ''), outfd, outhfd, outhfile)
else:
    code.assemble(outfd)
